version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - cd api && npm install
      - cd ../ui && npm install
  build:
    commands:
      - echo Build started on `date`
      - cd ../api && npm run build
      - cd ../ui && REACT_APP_GA_KEY=UA-162138850-1 npm run build
  post_build:
    commands:
      - cd .. && mkdir output
      - cp -r .ebextensions output
      - cp api/package.json output
      - cp api/package-lock.json output
      - mv api/build output/api
      - mv ui/build output/ui
artifacts:
  files:
    - '**/*'
  base-directory: output
